#!/bin/bash

result="65536"
plist="/usr/local/munki/managedsoftwareupdate"
if [ -e "${plist}" ] ; then
	version=$(${plist} -V)
	result=$(echo "${version}"|tr -d '.')
fi

echo "<result>${result}</result>"
